
services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
        POSTGRES_USER: platform_user
        POSTGRES_PASSWORD: strong_password
        POSTGRES_DB: platform_db

    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
